<div style="
    background-color: #7BAFD4;
    border-radius: 18px;
    padding: 22px 26px;
    display: flex;
    align-items: center;
    gap: 24px;
    margin-bottom: 18px;
">
    <img src="592_avatar_lr.png" alt="GEOG 592"
        style="width:110px;height:110px;border-radius:22px;">
    <div>
        <div style="
            font-family: Impact, 'Arial Black', Arial, sans-serif;
            font-size: 42px;
            font-weight: 900;
            letter-spacing: 2px;
            line-height: 1;
            color: white;
        ">GEOG 592</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 22px;
            font-weight: 700;
            color: #13294B;
            margin-top: 8px;
        ">GIS Programming</div>
        <div style="
            font-family: Arial, Helvetica, sans-serif;
            font-size: 16px;
            color: #13294B;
            margin-top: 6px;
        ">Module 2, Day 2: CSV example</div>
    </div>
</div>

# Module 2: Day 2
## Data verification: CSV example

Today we will work with:

```text
physical_NC_with_an_error.csv
```

The file contains North Carolina county-level health data. *It has intentional errors in at least one record.*

Instead of scanning it manually, we will investigate the file using Python to see if the data is internally consistent.


### Today you will learn to read, inspect, validate, and clean CSV files in python, using the dictionary concepts from Day 1.  You will also learn what a *Python package* is, and how to use one (the `csv` library).



# Recap: GeoJSON and fictionaries

On Day 1 we worked with dictionaries and nested GeoJSON-style structures, which were accessed like
```python
feature["properties"]["name"]
feature["geometry"]["coordinates"][0]
```
Today you will use a function from a Python package to convert a `.csv` file stored on the computer to a set of records that behave like dictionaries.

# Part 1: Packages

## What is a package?

A **package** (or **module**) is a collection of related objects, datatypes, and functions that _extend_ Python with additional tools for particular jobs (Read [this](https://docs.python.org/3/glossary.html#term-package) if you want to know the tiny difference between packages and modules; I don't.)  These are frequently called "libraries" in other programming languages.

Examples:

| module / package | Purpose |
|---|---|
| `csv` | Read and write CSV files |
| `math` | Provide mathematical functions like `sqrt` |
| `random` | Generate random numbers |
| `pandas` | Manipulate tabular data and DataFrames |
| `geopandas` | Work with geographic vector data |

To use a module, you `import` it.  You can also import some specific functions from the module.

Some modules are included automatically with Python. 

For example, the `import` statements below

```python
import math
import csv
```

work without installing anything.  After executing those lines, you can use anything in the `math` or `csv` library.

```python
from math import sqrt
```
also works without installing anything.  This import only makes the `sqrt` function available.


More specific packages, such as `pandas` and `geopandas`, normally need to be installed separately.



# Part 2: Open the CSV

The CSV file should be in the same folder as this notebook, so we can find it with the filename `"physical_NC_with_an_error.csv"`.

The `open()` function has two parameters, a string indicating the file's location, and a *mode* command indicating what we want to be able to do to the file.

Here we only need to read the file, so we will open it in read-only mode by passing the argument `"r"`.

In [4]:
import csv

filename = "physical_NC_with_an_error.csv"

with open(filename, "r") as file:
    reader = csv.DictReader(file)
    rows = list(reader)

print(rows)

[{'Year': 'Column1', 'StateAbbr': 'Column2', 'StateDesc': 'Column3', 'LocationName': 'Column4', 'DataSource': 'Column5', 'Category': 'Column6', 'Measure': 'Column7', 'Data_Value_Unit': 'Column8', 'Data_Value_Type': 'Column9', 'Data_Value': 'Column10', 'Data_Value_Footnote_Symbol': 'Column11', 'Data_Value_Footnote': 'Column12', 'Low_Confidence_Limit': 'Column13', 'High_Confidence_Limit': 'Column14', 'TotalPopulation': 'Column15', 'TotalPop18plus': 'Column16', 'LocationID': 'Column17', 'CategoryID': 'Column18', 'MeasureId': 'Column19', 'DataValueTypeID': 'Column20', 'Short_Question_Text': 'Column21', 'Geolocation': 'Column22'}, {'Year': '2023', 'StateAbbr': 'NC', 'StateDesc': 'North Carolina', 'LocationName': 'Cleveland', 'DataSource': 'BRFSS', 'Category': 'Health Risk Behaviors', 'Measure': 'No leisure-time physical activity among adults', 'Data_Value_Unit': '%', 'Data_Value_Type': 'Age-adjusted prevalence', 'Data_Value': '26.2', 'Data_Value_Footnote_Symbol': '', 'Data_Value_Footnote': 

## What did `DictReader` do?

A CSV is a table of rows and columns.  `csv.DictReader()` treats the *first* row of the CSV as the names of the columns, and then returns each subsequent row as a dictionary with the column names as the keys, and the content of that column as the value.  We turn this into a Python list of single row dictionaries called `rows` -- lists of dictionaries are a nice example of nested data structures.


Our CSV has a header row that looks like
| Year| StateAbbr | StateDesc| LocationName| DataSource|...|
|--|--|--|--|--|--|

That means a record in a row called `row` should be accessed like this:

```python
row["LocationName"]
```

rather than:

```python
row[3]
```


### Connection to yesterday

Yesterday a dictionary looked like:

```python
location = {
    "name": "A",
    "easting": 680100
}
```

and we retrieved a value with:

```python
location["name"]
```

A row produced by `csv.DictReader()` works the same way. When stored in our list, `rows`, we can call

```python
rows[2]["LocationName"]
```

to get the LocationName in the third row.  Notice: with `DictReader()`, the **column name becomes the dictionary key**.



> *Wait, what is `with` all about?*
>
> There is unfamiliar syntax (`with`) in the code above.  Why is it there? 
> You could also open a read-only file this way:
> ```python
>  file=open("my_first.csv","r")
>  ```
>
> However, it is good practice to *close* a file after you are done with it. Instead of 
> remembering to put `file.close()` somewhere in your program, you can use the `with` statement. 
>  ```python
>   with open(filename, "r") as file:
>       reader = csv.DictReader(file)
>       rows = list(reader)
>   #all done with the file   
>   ```
> `with` begins an (indented!) code block and assigns the value returned by `open(...)` 
> to the variable `file`. **This instructs python to call `file.close()` behind the scenes when the code block ends.**
>
> > The details of using `with` don't matter for us today, but if you always open files this way, it won't hurt.


In [5]:
print("Number of rows:", len(rows))
print("Number of columns:", len(reader.fieldnames))
print("Column names:")
print(reader.fieldnames)

Number of rows: 101
Number of columns: 22
Column names:
['Year', 'StateAbbr', 'StateDesc', 'LocationName', 'DataSource', 'Category', 'Measure', 'Data_Value_Unit', 'Data_Value_Type', 'Data_Value', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit', 'TotalPopulation', 'TotalPop18plus', 'LocationID', 'CategoryID', 'MeasureId', 'DataValueTypeID', 'Short_Question_Text', 'Geolocation']


# Part 3: First, inspect the data

Before calculating anything let's look at the first 3 rows. 


In [6]:
for row in rows[:3]:
    print(row)


{'Year': 'Column1', 'StateAbbr': 'Column2', 'StateDesc': 'Column3', 'LocationName': 'Column4', 'DataSource': 'Column5', 'Category': 'Column6', 'Measure': 'Column7', 'Data_Value_Unit': 'Column8', 'Data_Value_Type': 'Column9', 'Data_Value': 'Column10', 'Data_Value_Footnote_Symbol': 'Column11', 'Data_Value_Footnote': 'Column12', 'Low_Confidence_Limit': 'Column13', 'High_Confidence_Limit': 'Column14', 'TotalPopulation': 'Column15', 'TotalPop18plus': 'Column16', 'LocationID': 'Column17', 'CategoryID': 'Column18', 'MeasureId': 'Column19', 'DataValueTypeID': 'Column20', 'Short_Question_Text': 'Column21', 'Geolocation': 'Column22'}
{'Year': '2023', 'StateAbbr': 'NC', 'StateDesc': 'North Carolina', 'LocationName': 'Cleveland', 'DataSource': 'BRFSS', 'Category': 'Health Risk Behaviors', 'Measure': 'No leisure-time physical activity among adults', 'Data_Value_Unit': '%', 'Data_Value_Type': 'Age-adjusted prevalence', 'Data_Value': '26.2', 'Data_Value_Footnote_Symbol': '', 'Data_Value_Footnote': ''

Visual inspection is fine for now: one of those records should look suspicious.

We can automate data cleaning, but our eyes are really good at seeing patterns and errors. 

We know that the first row has an error since each record is 'Column...'

We can clean the data by removing that row from the dataset. 




In [7]:
noFirstRow = rows[1:]
print("now we have", len(noFirstRow), 'rows, and before we had', len(rows), 'rows')

now we have 100 rows, and before we had 101 rows


If you recall the assessment, our task with this csv was to create a choropleth with 'Data Value'. 

So let's simplify the data manually, keeping 
- "LocationID" (for making the join), 
- "Data_Value" (for the choropleth), and
- "LocationName" (for cross-checking the join, or as another potential join field) 

In [8]:
selected_columns = []

for row in noFirstRow:

    selected_columns.append({
        "LocationID": row["LocationID"],
        "LocationName": row["LocationName"],
        "Data_Value": row["Data_Value"]
    })

for row in selected_columns[:5]:
    print(row)

{'LocationID': '37045', 'LocationName': 'Cleveland', 'Data_Value': '26.2'}
{'LocationID': '37023', 'LocationName': 'Burke', 'Data_Value': '26.7'}
{'LocationID': '37001', 'LocationName': 'Alamance', 'Data_Value': '23.7'}
{'LocationID': '37013', 'LocationName': 'Beaufort', 'Data_Value': '26'}
{'LocationID': '37027', 'LocationName': 'Caldwell', 'Data_Value': '25.5'}


Notice how we created an empty list, and then used `append` to add our simplified records, selecting only the columns that we are interested in keeping. 

Notice that we are appending a dictionary, so we create a *list of dictionaries*, which is the same as the data structure produced by the `DictReader()` code block.



In [9]:
selected_columns[0] # you should see a shortened dictionary, which is the first row. 

{'LocationID': '37045', 'LocationName': 'Cleveland', 'Data_Value': '26.2'}

# Part 4: Expected data types

Notice that CSV values read by `DictReader()` are Python **strings**.

Even a value in the CSV such as ~26.2~ is stored in the dictionary for each row as '26.2'.

Let's verify that.


In [10]:
value = selected_columns[0]["Data_Value"]
print(value,"is datatype",type(value))



26.2 is datatype <class 'str'>


### Important: CSV values are read as strings.

With the built-in `csv` module, values from the file are read as strings.
If you want to perform arithmetic, you must explicitly convert the values:

```python
locationID = int(selected_columns["LocationID"])
value = float(selected_columns["Data_Value"])
```

> This is one reason datatype checking is important when working directly with CSV files.


In [11]:
print(type(selected_columns[1]["LocationID"]))
print(type(selected_columns[1]["Data_Value"]))
print(type(selected_columns[1]["LocationName"]))


<class 'str'>
<class 'str'>
<class 'str'>


So type checking with the `csv` module is not finding out what datatype is stored in the records in the list of dictionaries, since that's a `<class 'str'>`. It's really finding out if the record
can be converted to the type that the column is supposed to contain.

For example:
- `LocationID` should successfully convert to an integer;
- `Data_Value` should successfully convert to a float;
- `LocationName` should behave like text.


# Part 5: Create simple type-checking functions

Recall from the previous notebook : 

*A `try` / `except` lets us test a type conversion without crashing the notebook.*


In [12]:
def can_be_int(value):
    try:
        int(value)
        return True
    except ValueError:
        return False


def can_be_float(value):
    try:
        float(value)
        return True
    except ValueError:
        return False


Try them:


In [13]:
print(can_be_int("35001"))
print(can_be_int("Column1"))

print(can_be_float("26.2"))
print(can_be_float("Column10"))


True
False
True
False


# Part 6: Hunt for more datatype inconsistencies

## Check `Location ID`

Every value in `LocationID` should be convertible to an integer.


In [14]:
error_found = False

for row in selected_columns:
    value = row["LocationID"]

    if value == "":
        print(
            row["LocationName"],
            "is missing a LocationID"
        )
        error_found = True

    elif not can_be_int(value):
        print(
            row["LocationName"],
            "has suspicious LocationID:",
            value
        )
        error_found = True

if not error_found:
    print("Everything looks good.")

Rockingham has suspicious LocationID: 3715@


We have now detected the a record by **datatype inconsistency checking**, not merely by looking at it.

For further checks, please note: that geoID fields, like `Geolocation` in this csv file, should probably be stored as strings since they might start with trailing zeros which are lost in conversion to numerical types. *If a Geolocation does not convert to an integer, there is still an error in the record.* 

Instead of attempting to convert each field, you could check for special characters in the record using regular expressions (also called 'regex', provided by python module `re`). 

This is a useful syntax for expressing patterns that you might want your string to match, but the syntax is easy to forget:

**Example:** regular expression matching only non-alphanumeric charcters: 
```python 
"r[^A-Za-z0-9 ]"
```

**Example:** regular expression matching most names pronounced like "Catherine" in English:
```python 
r'^[KC]ath(?:er|ar)?(?:ine|yn|yne)$'
```

Luckily, AI is pretty good at helping create regex. 

The following use of the `re` module was generated using AI.
It's ok if you do not understand it, but notice that we were also able to find the error.

In [15]:
## checking for special characters using Regex.
import re 

for row in selected_columns:
    value = row["LocationID"]

    if re.search(r"[^A-Za-z0-9 ]", value):
        print(
            row["LocationName"] + "'s",
            "LocationID"+ '('+ row["LocationID"] + ')',
            "contains a special character"
        )

Rockingham's LocationID(3715@) contains a special character


For this case we can fix it by searching for the cell with the value "3715@" and changing it to "37157", the correct LocationID for Rockingham.

In [16]:
for row in selected_columns:
    if row["LocationID"] == "3715@":
        row["LocationID"] = "37157"

## Check `Data_Value`

Every non-empty `Data_Value` should be convertible to a float.


In [17]:
error_found = False
missing_or_zero_count = 0

for row in selected_columns:
    value = row["Data_Value"]

    # Check datatype consistency
    if value != "" and not can_be_float(value):
        print(
            row["LocationName"],
            "has suspicious Data_Value:",
            value
        )
        error_found = True

    # Check completeness
    if value == "" or value == "0":
        missing_or_zero_count += 1
        print(
            row["LocationName"],
            "has an empty or zero Data_Value"
        )

if not error_found:
    print("All Data_Value entries have a consistent numeric format.")

if missing_or_zero_count == 0:
    print("All Data_Value entries are complete and non-zero.")
else:
    print(
        "Number of empty or zero Data_Value entries:",
        missing_or_zero_count
    )

All Data_Value entries have a consistent numeric format.
All Data_Value entries are complete and non-zero.


Write code to check that the cells in `LocationName` column are not empty. 


In [18]:
# Write code here 
# (it is ok if you copy-paste from the previous test, but try to understand what needs to be done and change it to just check that the the cells in `LocationName` column are not empty)
is_empty = False

for i in selected_columns:
    x = i["Data_Value"]
    if x == "" and not can_be_float(x):
        print(f"Column {i} is empty")
        is_empty = True

Below, we export the cleaned csv. 

BTW, this requires a series of steps in Python, but it will be much easier once we use Pandas. 

In [19]:
fieldnames = selected_columns[0].keys() ## this gets the names of the columns (or keys)

with open("selected_columns.csv", "w", newline="") as file:
    writer = csv.DictWriter(file, fieldnames = fieldnames) 
    writer.writeheader()
    writer.writerows(selected_columns)

# Data exploration
Now that we have clean records, find counties where physical inactivity is greater than 30%.


In [20]:
for row in selected_columns:
    value = float(row["Data_Value"])

    if value > 30:
        print(row["LocationName"], value)


Anson 31.7
Bertie 31.8
Halifax 33.1
Richmond 30.9
Edgecombe 31.7
Northampton 30.2
Greene 31.6
Wilson 30.6
Washington 32.0
Robeson 34.9
Lenoir 32.3
Hertford 31.6
Warren 31.0
Scotland 32.7


# What You Should Know for Programming Skills Check #2

Programming Skills Check #2 will include ideas from **both Module 2 days**.

## Day 1: GeoJSON Structures

You should be able to:

- identify a list;
- identify a dictionary;
- explain the difference between an index and a key;
- follow a nested structure;
- determine what a GeoJSON expression returns.

For example, given:

```python
geojson = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "name": "A"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [680100, 3975200]
            }
        }
    ]
}
```

you should be able to determine the results of expressions such as:

```python
geojson["type"]
```

```python
geojson["features"][0]["properties"]["name"]
```

```python
geojson["features"][0]["geometry"]["coordinates"]
```

```python
geojson["features"][0]["geometry"]["coordinates"][1]
```

## Day 2:CSV data cleaning

You should be able to:

- explain what a library is;
- write `import csv`;
- explain what `csv.DictReader()` does;
- access a value using `row["ColumnName"]`;
- understand that CSV values initially arrive as strings;
- use `int()` and `float()` conversions;
- use `try` / `except` to test whether a value can be converted;
- loop through records;
- use `if` to flag inconsistent records;
- use a counter;
- recognize missing values;
- identify suspicious values;
- explain why opening a file successfully does not prove that the data are correct.


## Quick Paper Practice

These are similar to the kinds of things you should be able to work out without running Python.

### 1. What does this return?

```python
row = {
    "LocationID": "37063",
    "LocationName": "Durham",
    "Data_Value": "24.5"
}

row["LocationName"]
```

### 2. What datatype is returned?

```python
type(row["Data_Value"])
```

### 3. What does this condition check?

```python
if value == "":
```

### 4. What will this print?

```python
values = ["20.5", "", "18.2", "", "30.1"]

missing_count = 0

for value in values:
    if value == "":
        missing_count = missing_count + 1

print(missing_count)
```

### 5. What is wrong with this code?

```python
value = row["Data_Value"]

if value > 30:
    print(row["LocationName"])
```

### 6. Compare these two expressions

```python
row["LocationName"]
```

```python
geojson["features"][0]["properties"]["name"]
```

Both retrieve a name.

Why does the GeoJSON expression require more steps?
